apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        instrumentation.opentelemetry.io/inject-python: "opentelemetry-operator-system/elastic-instrumentation"
    spec:
      containers:
      - name: backend
        image: albertodimanuel275/backend-demo-onboarding:latest
        ports:
        - containerPort: 5000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-config
              key: OPENAI_API_KEY
        - name: ELASTIC_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: backend-config
              key: ELASTIC_ENDPOINT
        - name: ELASTIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-config
              key: ELASTIC_API_KEY
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: backend-config
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_HEADERS
          valueFrom:
            secretKeyRef:
              name: backend-config
              key: OTEL_EXPORTER_OTLP_HEADERS
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP